### ISSUE TITLE
How to get this awesome project run?

### ISSUE THREAD

**Issue by jindulys** [twitterdev/furni-ios#2]
I am following the instructions in readme. But I get stuck in this two instructions.

4, Sign in with your Fabric account, select the Furni Xcode workspace and choose an organization.
5, Use the Fabric app for each Kit to obtain your API keys and facilitate the onboarding process.

What do you mean by choosing an organization?
Fabric app has a list of Kit, like Crashlytics, Answer, Twitter, etc, should i install all of them? What is API keys? 

Thx for your help

**Comment by mikebonnell** [comment]
Hey @jindulys,

You would need to sign up at Fabric.io, create an account and then use the organization that is created during the sign up flow. That will generate the API keys that you need to sign up.

**Comment by jindulys** [comment]
I see, thank you for your response.

**Comment by judi0713** [comment]
If you can't install, crashed because "[Digits] Cannot find kit info.".You can try install Twitter first.
