### ISSUE TITLE
'Attempted to call TwitterKit methods before calling the requisite start methods; you must call +[Fabric with:@[Twitter class]] before using the methods on TwitterKit

### ISSUE THREAD

**Issue by 03128crz** [twitterdev/furni-ios#5]
I already flow the step in  readme. But when I run app , get blew error

Terminating app due to uncaught exception 'TWTRInvalidInitializationException', reason: 'Attempted to call TwitterKit methods before calling the requisite start methods; you must call +[Fabric with:@[Twitter class]] before using the methods on TwitterKit. If you are not storing your consumerKey and consumerSecret in your application's info.plist you must also call -[TwitterKit startWithConsumerKey:consumerSecret:] before calling +[Fabric with:]'

**Comment by mikebonnell** [comment]
That error usually means that the API key isn't in your info.plist or that you're initializing TwitterKit without having an API key and secret before the init. Here are some additional examples to help: [https://docs.fabric.io/ios/twitter/twitterkit-setup.html#integrate-with-your-app](url)

For reference, these types of questions are best raised at [TwitterCommunity.com/c/fabric](url)

**Comment by 03128crz** [comment]
Thanks ,solved

**Comment by fr33kill** [comment]
I have API key and secret in the info.plist. Still, it is crashing with the same error. Recently, I changed the API key and secret.

**Comment by mikebonnell** [comment]
As mentioned previously, these types of questions are best asked at [Twittercommunity.com/c/fabric](https://twittercommunity.com/c/fabric), please post there with more information - such as how you're initializing Fabric.

**Comment by i-schuetz** [comment]
@mikebonnell where do I report that the Twitter community login is broken?

Also, couldn't find this issue there. Wanted to open it but I can't.
